"""add orders model

Revision ID: 62c142349299
Revises: f4456eced18a
Create Date: 2020-06-11 19:41:44.395195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c142349299'
down_revision = 'f4456eced18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchaser_email', sa.String(length=255), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('payment_reference_id', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order'))
    )
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_store_user_id_user'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_store_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('order')
    # ### end Alembic commands ###
